-- Maintenance Module Tables (applications database)
-- Used by: src/p.maintenance/

-- Main vehicle maintenance requests table
CREATE TABLE IF NOT EXISTS `vehicle_svc` (
  `req_id` int NOT NULL AUTO_INCREMENT,
  `req_date` date DEFAULT NULL,
  `asset_id` int DEFAULT NULL,
  `entry_code` varchar(10) DEFAULT NULL,
  `vehicle_id` int DEFAULT NULL,
  `register_number` varchar(100) DEFAULT NULL,
  `ramco_id` varchar(6) DEFAULT NULL,
  `ctc_m` varchar(50) DEFAULT NULL,
  `costcenter_id` int DEFAULT NULL,
  `location_id` int DEFAULT NULL,
  `svc_opt` text,
  `st` text,
  `odo_start` int DEFAULT '0',
  `odo_end` int DEFAULT '0',
  `req_comment` text,
  `req_upload` varchar(255) DEFAULT NULL,
  `verification_comment` text,
  `verification_stat` int DEFAULT '0',
  `verification_date` datetime DEFAULT NULL,
  `rejection_comment` text,
  `ws_id` int DEFAULT '0',
  `major_opt` text,
  `major_svc_comment` text,
  `recommendation` text,
  `recommendation_stat` int DEFAULT '0',
  `recommendation_date` datetime DEFAULT NULL,
  `approval` text,
  `approval_stat` int DEFAULT '0',
  `approval_date` datetime DEFAULT NULL,
  `drv_stat` int DEFAULT NULL,
  `drv_date` datetime DEFAULT NULL,
  `form_upload` text,
  `form_upload_date` date DEFAULT NULL,
  `late_notice` text,
  `late_notice_date` datetime DEFAULT NULL,
  `svcComp` text,
  `stAdm` varchar(200) DEFAULT NULL,
  `instWs` text,
  `appStat` varchar(25) DEFAULT NULL,
  `recPIC` varchar(100) DEFAULT NULL,
  `recDate` date DEFAULT NULL,
  `appPIC` varchar(100) DEFAULT NULL,
  `appDate` date DEFAULT NULL,
  `emailStat` int DEFAULT '0',
  `stAdmRem` varchar(300) DEFAULT NULL,
  `extra_mileage` varchar(6) DEFAULT NULL,
  `date_create` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `inv_status` int DEFAULT '0',
  `drv_cancel_comment` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`req_id`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_ramco_id` (`ramco_id`),
  KEY `idx_req_date` (`req_date`),
  KEY `idx_costcenter_id` (`costcenter_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12000 DEFAULT CHARSET=latin1;

-- Service types/categories
CREATE TABLE IF NOT EXISTS `svctype` (
  `svcTypeId` int NOT NULL AUTO_INCREMENT,
  `svcType` varchar(50) DEFAULT NULL,
  `svcOpt` int NOT NULL DEFAULT '0',
  `group_desc` text,
  `orders` int DEFAULT NULL,
  `appearance` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`svcTypeId`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=latin1;

-- Pool car booking requests
CREATE TABLE IF NOT EXISTS `poolcar` (
  `pcar_id` int NOT NULL AUTO_INCREMENT,
  `pcar_datereq` date DEFAULT NULL,
  `pcar_empid` varchar(7) DEFAULT NULL,
  `ctc_m` varchar(12) DEFAULT NULL,
  `dept_id` int NOT NULL DEFAULT '0',
  `loc_id` int NOT NULL DEFAULT '0',
  `pcar_booktype` varchar(10) DEFAULT NULL,
  `pcar_type` int NOT NULL DEFAULT '0',
  `pcar_datefr` datetime DEFAULT NULL,
  `pcar_dateto` datetime DEFAULT NULL,
  `pcar_day` int NOT NULL DEFAULT '0',
  `pcar_hour` int DEFAULT '0',
  `pcar_dest` text,
  `pcar_purp` text,
  `pcar_opt` varchar(150) DEFAULT NULL,
  `pass` text,
  `vehicle_id` int NOT NULL DEFAULT '0',
  `asset_id` int DEFAULT NULL,
  `pcar_driver` varchar(6) DEFAULT NULL,
  `pcar_rem` text,
  `recommendation` text,
  `recommendation_stat` int NOT NULL DEFAULT '0',
  `recommendation_date` datetime DEFAULT NULL,
  `approval` text,
  `approval_stat` int NOT NULL DEFAULT '0',
  `approval_date` datetime DEFAULT NULL,
  `pcar_driver_chklist` text,
  `pcar_odo_start` varchar(6) DEFAULT NULL,
  `pcar_odo_end` varchar(6) DEFAULT NULL,
  `pcar_condition` text,
  `pcar_condition_rem` text,
  `pcar_driver_upload` text,
  `pcar_retdate` datetime DEFAULT NULL,
  `tng_id` int DEFAULT NULL,
  `fleetcard_id` int DEFAULT NULL,
  `tng_usage` decimal(10,2) NOT NULL DEFAULT '0.00',
  `pcar_stat` varchar(10) DEFAULT NULL,
  `pcar_dt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pcar_id`),
  KEY `idx_vehicle_id` (`vehicle_id`),
  KEY `idx_pcar_datereq` (`pcar_datereq`),
  KEY `idx_pcar_stat` (`pcar_stat`)
) ENGINE=InnoDB AUTO_INCREMENT=836 DEFAULT CHARSET=latin1;

-- Asset data (vehicles)
CREATE TABLE IF NOT EXISTS `assetdata` (
  `id` int NOT NULL AUTO_INCREMENT,
  `entry_code` varchar(50) DEFAULT NULL,
  `vehicle_id` int DEFAULT NULL,
  `manager_id` int DEFAULT NULL,
  `type_id` int DEFAULT NULL,
  `category_id` int DEFAULT NULL,
  `brand_id` int DEFAULT NULL,
  `model_id` int DEFAULT NULL,
  `costcenter_id` int DEFAULT NULL,
  `department_id` int DEFAULT NULL,
  `location_id` int DEFAULT NULL,
  `ramco_id` varchar(10) DEFAULT NULL,
  `purchase_id` int DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  `purchase_year` year DEFAULT NULL,
  `vehicle_regno` varchar(20) DEFAULT NULL,
  `register_number` varchar(50) DEFAULT NULL,
  `transmission` varchar(15) DEFAULT NULL,
  `fuel_type` varchar(6) DEFAULT NULL,
  `card_id` int DEFAULT NULL,
  `classification` varchar(50) DEFAULT NULL,
  `record_status` varchar(50) DEFAULT NULL,
  `purpose` varchar(50) DEFAULT NULL,
  `condition_status` varchar(50) DEFAULT NULL,
  `action` varchar(20) DEFAULT NULL,
  `disposed_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_vehicle_id` (`vehicle_id`),
  KEY `idx_costcenter_id` (`costcenter_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7861 DEFAULT CHARSET=utf8mb3;

